config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :photos do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'

    collection do 
      get 'search'
    end
  end

  root "photos#index"
  get "home" => "pages#home"

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	acts_as_likeable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  searchkick

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos

  
  acts_as_followable

  acts_as_follower

  acts_as_liker
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
      if user_signed_in?
        @user_photos = Photo.where(user_id: current_user.id)
        @followees_photos = Photo.where(user_id: current_user.followees(User).map(&:id))
        @photos = @followees_photos || @user_photos
      end

      redirect_to home_path unless user_signed_in? 
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = current_user.photos.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.build(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end

      unless @photo == current_user.photos.first
        current_user.photos.first.destroy
      end
    end


  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :image)
    end
end

app/controllers/socializations_controller.rb
class SocializationsController < ApplicationController

  before_filter :load_socializable

  def follow
    current_user.follow!(@socializable)
    redirect_to :back
  end

  def unfollow
    current_user.unfollow!(@socializable)
    redirect_to :back
  end

  def like
  	current_user.like!(@socializable)
  	redirect_to :back
  end

  def unlike
  	current_user.unlike!(@socializable)
  	redirect_to :back
  end

 

private
  def load_socializable
    @socializable =
      case
      when id = params[:user_id]
        User.find(id)
      when id = params[:photo_id]
        Photo.find(id)
      else
        raise ArgumentError, "Unsupported socializable model, params: " +
                             params.keys.inspect
      end
    raise ActiveRecord::RecordNotFound unless @socializable
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	def search

		if params[:search].present?
			@users = User.search(params[:search])
		else
			@users = User.all
		end
  	end


	def show
		@user = User.find(params[:id])
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/socializations_helper.rb
module SocializationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Streamline", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <% if user_signed_in? %>
        <%= form_tag search_users_path, method: :get, class: "navbar-form pull-left", role: "search" do %>
          
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
      

        <% end %>
      <% end %>


      

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li><%= link_to "New Photo", new_photo_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Hi, <%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li><!-- /.dropdown -->
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul><!-- /.navbar-right -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
	<div id="main_content", class="container">
		<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: 'alert-alert#{name}') %>
		<% end %>
		<div id="content" class="col-md-12">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/pages/home.html.erb
<%= render 'photos/index' if user_signed_in? %>


<div class="jumbotron text-center vertical-center">
	<h1>Welcome!</h1>
	<h4>With Streamline, you can feature your most important photo of the moment and share it with your friends. Everytime you upload a new one, the old one goes away.</h4>
	<br />
		<p>
			<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>

</div>

app/views/photos/_form.html.erb
  <%= form_for @photo, html: { multipart: true } do |f| %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

        <ul>
        <% @photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="panel panel-default">
    <div class="panel-body">

      <div class="field form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= f.label :caption %><br>
        <%= f.text_area :caption, class: "form-control" %>
      </div>
      <div class="actions form-group">
        <%= f.submit "Post", class: "btn btn-primary btn-small" %>
      </div>
    </div> <!-- panel-body -->
  </div> <!-- panel -->
  <% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
  
<% if current_user.followees_count == 0 %>
  <div class="jumbotron text-center">
    <h2>Looks like you aren't following anyone yet.</h2>
    <br />
    <h4>Use the searchbox above to find people you want to follow!</h4>
  </div>
<% else %>
  <div id="photos">
    <div class="photo-panel panel panel-default">
      <% @photos.each do |photo| %>
          

            <%= link_to image_tag(photo.image.url), user_path(photo.user), class: "img-responsive wide_img" %>

            <div class="panel-body">

              <h4><%= photo.caption %></h4>
              <p>Posted <%= time_ago_in_words(photo.created_at) %> ago by <strong><%= link_to photo.user.name, user_path(photo.user) %></strong></p>
              <p>
                <% if photo.likers_count.nil? %> 
                  <span> 0 </span>
                <% else %>
                  <%= photo.likers_count %>
                <% end %>

                Likes
              </p>
          
              <% unless photo.liked_by?(current_user) %>
                <%= link_to "Like", photo_like_path(photo), method: :post, class: "btn btn-default btn-sm pull-left" %>
              <% else %>
                <%= link_to "Unlike", photo_unlike_path(photo), method: :post, class: "btn btn-default btn-sm pull-left" %>
              <% end %>

              <% if photo.user == current_user %>
                <div class="text-right">
                  <%= link_to 'Edit', edit_photo_path(photo) %></td>
                  <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div> <!-- text-right -->
              <% end %>

            </div> <!-- panel-body -->
          
          
      <% end %>
      <div> <!-- panel-default -->
  </div>
<% end %>
  


  

app/views/photos/new.html.erb
<div class="col-md-4 col-md-offset-4">

	<h1>New Photo</h1>

	<%= render 'form' %>

	<%= link_to 'Back', photos_path %>

</div>

app/views/photos/show.html.erb
<p>
  <%= image_tag @photo.image.url %>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', root_path %>

app/views/users/search.html.erb
<div class="row text-center">
	<% @users.each do |user| %>
		<h2><%= link_to user.name, user_path(user) %></h2>
	<% end %>
</div>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %></h1>

	<% unless current_user == @user %>
		<% if current_user.follows?(@user) == false %>
			<%= link_to "Follow", user_follow_path(@user), method: :post, class: "btn btn-default btn-sm" %>
		<% else %>
			<%= link_to "Unfollow", user_unfollow_path(@user), method: :post, class: "btn btn-default btn-sm" %>
		<% end %>
	<% end %>
	<div id="center">
		<div id="user-photos", class="col-md-4 col-md-offest-4">
			<div class="panel panel-default">
				<% @user.photos.each do |photo| %>
					<%= image_tag photo.image.url %>
					<div class="panel-body">
				    	<h4><%= photo.caption %></h4>
				    	<p>Posted <%= time_ago_in_words(photo.created_at) %> ago</p>
					</div>

					<% if photo.user == current_user %>
			            <div class="text-right">
				            <%= link_to 'Edit', edit_photo_path(photo) %></td>
				            <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
			            </div> <!-- text-right -->
	            	<% end %>

			    <% end %>
			</div>	<!-- panel-default -->
		</div> <!-- user-photos -->
	</div> <!-- center -->